virustotal:
  enabled: true
  api_key: PUT_YOUR_VT_API_KEY_HERE
  rate_limit:
    requests_per_minute: 4
urlhaus:
  enabled: true
  rate_limit:
    requests_per_minute: 10
malwarebazaar:
  enabled: true
  api_key: YOUR_MALWAREBAZAAR_AUTH_KEY_HERE
  rate_limit:
    requests_per_minute: 10
malshare:
  enabled: true
  api_key: 23354fec5b58c46f8943dc88403595fb53568f77e877dd58526a470a743504ea
  rate_limit:
    requests_per_minute: 10
hybrid_analysis:
  enabled: true
  api_key: w09aojr5933e9590snix99nhe111f463v976ypfb49acc1bfzhehgb4mb497583a
  rate_limit:
    requests_per_minute: 5
hashlookup:
  enabled: true
  rate_limit:
    requests_per_minute: 20
otx:
  enabled: true
  api_key: ''
  rate_limit:
    requests_per_minute: 10
threatfox:
  enabled: true
  rate_limit:
    requests_per_minute: 10
cache:
  dir: cache
  ttl_minutes: 1440
vendor_allowlist:
- Microsoft
- Kaspersky
- BitDefender
