virustotal:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 4

urlhaus:
  enabled: true
  rate_limit:
    requests_per_minute: 10

malwarebazaar:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 10

malshare:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 10

hybrid_analysis:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 5

hashlookup:
  enabled: true
  rate_limit:
    requests_per_minute: 20

otx:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 10

threatfox:
  enabled: true
  rate_limit:
    requests_per_minute: 10

cache:
  dir: cache
  ttl_minutes: 1440

vendor_allowlist:
- Microsoft
- Kaspersky
- BitDefender
- Avast
- CrowdStrike Falcon
- ESET-NOD32
- Symantec
- TrendMicro-HouseCall
- Arctic Wolf
