virustotal:
  enabled: true
  api_key: "PUT_YOUR_VT_API_KEY_HERE"
  rate_limit:
    requests_per_minute: 4

urlhaus:
  enabled: true
  rate_limit:
    requests_per_minute: 10

malwarebazaar:
  enabled: true
  api_key: "OPTIONAL_MALWAREBAZAAR_AUTH_KEY"
  rate_limit:
    requests_per_minute: 10

malshare:
  enabled: true
  api_key: "PUT_MALSHARE_API_KEY_HERE"
  rate_limit:
    requests_per_minute: 10

hybrid_analysis:
  enabled: true
  api_key: "PUT_HYBRID_ANALYSIS_API_KEY_HERE"
  rate_limit:
    requests_per_minute: 5

hashlookup:
  enabled: true
  rate_limit:
    requests_per_minute: 20

otx:
  enabled: true
  api_key: "PUT YOUR API KEY HERE"
  rate_limit:
    requests_per_minute: 10

threatfox:
  enabled: true
  rate_limit:
    requests_per_minute: 10

cache:
  dir: "cache"
  ttl_minutes: 1440

vendor_allowlist:
  - Microsoft
  - Kaspersky
  - BitDefender
